#!/usr/bin/env bash

set -eu pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Install the linux packages needed
#?? 1.0.0
##?
##? Usage:
##?   install_custom

log::note "Installing Flatpak"

sudo pacman -S --needed --noconfirm flatpak

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

log::note "Flatpak installed"

exit 0
