## Colors configuration
[colors.primary]
background = "#181818"
foreground = "#d0cabe"

[colors.normal]
black   = "#181818"
red     = "#D49721"
green   = "#9D8E76"
yellow  = "#447E80"
blue    = "#AB5F82"
magenta = "#B26587"
cyan    = "#478688"
white   = "#d0cabe"

[colors.bright]
black   = "#918d85"
red     = "#D49721"
green   = "#9D8E76"
yellow  = "#447E80"
blue    = "#AB5F82"
magenta = "#B26587"
cyan    = "#478688"
white   = "#d0cabe"
