## Colors configuration
[colors.primary]
background = "#000101"
foreground = "#86b7c3"

[colors.normal]
black   = "#000101"
red     = "#135170"
green   = "#205B75"
yellow  = "#19637C"
blue    = "#145D81"
magenta = "#1A6B88"
cyan    = "#217A91"
white   = "#86b7c3"

[colors.bright]
black   = "#5d8088"
red     = "#135170"
green   = "#205B75"
yellow  = "#19637C"
blue    = "#145D81"
magenta = "#1A6B88"
cyan    = "#217A91"
white   = "#86b7c3"
