# Hyprland Window Rules (0.53+ syntax)
# Syntax: windowrule = match:field value, RULE value

# Floating apps
windowrule = match:class foot-float|alacritty-float|kitty-float, float on
windowrule = match:class yad|nm-connection-editor|org.pulseaudio.pavucontrol, float on
windowrule = match:class polkit-gnome-authentication-agent-1|kvantummanager|qt5ct|qt6ct, float on
windowrule = match:class feh|viewnior|gimp|MPlayer, float on
windowrule = match:class VirtualBox Manager|qemu|Qemu-system-x86_64, float on
windowrule = match:title File Operation Progress, float on
windowrule = match:title Confirm to replace files, float on

# Thunar's rename window
windowrule = match:class thunar, match:title Rename.*, float on

# Yad window
windowrule = match:class Yad|yad, float on
windowrule = match:class Yad|yad, size 60% 64%

# Viewnior window
windowrule = match:class viewnior, size 60% 64%
windowrule = match:class viewnior, center on

# Alacritty floating geometry
windowrule = match:class Alacritty|alacritty|alacritty-float, size 785 450

# Fullscreen animations
windowrule = match:class foot-full|alacritty-full|kitty-full, animation slide down
windowrule = match:class wlogout, animation slide up

# Firefox
windowrule = match:class firefox, match:title (Picture-in-Picture), float on
# windowrule = match:class firefox, match:title (Picture-in-Picture), size 50%
windowrule = match:class firefox, match:title (Picture-in-Picture), move 100%-w-40 100%-w-40

# Virt-Manager - don't let it grab Hyprland shortcuts
windowrule = match:class virt-manager, no_shortcuts_inhibit on

windowrule = tag +music, match:title ^([Ss]ymphony)$
windowrule = tag +music, match:class ^([Hh]armony)$
windowrule = match:title ^(Developer Tools - http://localhost:5173/)$, tag +multimedia
windowrule = match:class ^(com.rtosta.zapzap)$, tag +im

windowrule = workspace 5, match:tag music*
windowrule = workspace 7, match:tag im*
windowrule = workspace 9 silent, match:tag multimedia*
windowrule = match:class ^(FreeCAD)$, tag +music
# Layer Rules
# layerrule = animation slide, rofi
# layerrule = animation slide, notifications
