hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("dunst")
	hl.exec_cmd("dbus-update-activation-environment --all")
	hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=gpg")
	hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=pkcs11")
	hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=secrets")
	hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=ssh")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("~/.config/hypr/xdg.sh >> /tmp/xdg.sh.log 2>&1")
	hl.exec_cmd("Thunar --daemon")
	hl.exec_cmd("~/.config/hypr/start-in-tray.sh")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprland-per-window-layout")
	hl.exec_cmd("sh -c 'killall -wq vicinae-server 2>/dev/null; vicinae server --replace'")
end)
