color0 #424750
color1 #ffb4ab
color2 #a7c8ff
color3 #b8c7e5
color4 #eeb1fa
color5 #a7c8ff
color6 #b8c7e5
color7 #e2e2e8
color8 #8d919b
color9 #ffb4ab
color10 #a7c8ff
color11 #b8c7e5
color12 #eeb1fa
color13 #a7c8ff
color14 #b8c7e5
color15 #e2e2e8

cursor                #e2e2e8
cursor_text_color     #111317
background            #111317
foreground            #e2e2e8
selection_foreground  #c3c6d1
selection_background  #424750
active_border_color   #a7c8ff
inactive_border_color #424750
url_color             #a7c8ff

active_tab_foreground   #003061
active_tab_background   #a7c8ff
inactive_tab_foreground #c3c6d1
inactive_tab_background #424750
cursor_trail_color      #c3c6d1
