color0 #40484d
color1 #ffb4ab
color2 #8dcff4
color3 #b1cada
color4 #e3b7f5
color5 #8dcff4
color6 #b1cada
color7 #e1e3e5
color8 #8a9298
color9 #ffb4ab
color10 #8dcff4
color11 #b1cada
color12 #e3b7f5
color13 #8dcff4
color14 #b1cada
color15 #e1e3e5

cursor                #e1e3e5
cursor_text_color     #111416
background            #111416
foreground            #e1e3e5
selection_foreground  #c0c7ce
selection_background  #40484d
active_border_color   #8dcff4
inactive_border_color #40484d
url_color             #8dcff4

active_tab_foreground   #003549
active_tab_background   #8dcff4
inactive_tab_foreground #c0c7ce
inactive_tab_background #40484d
cursor_trail_color      #c0c7ce
