# Plugins Declaration
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'Morantron/tmux-fingers'

set -g @plugin 'alexwforsythe/tmux-which-key' #trigger prefix + space
set -g @plugin 'caiogondim/maglev'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-net-speed'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'
set -g @plugin 'aserowy/tmux.nvim'

# Plugin Options
## tmux-fingers
bind -n M-f run -b "#{@fingers-cli} start #{pane_id}"
bind u run -b "#{@fingers-cli} start #{pane_id} --patterns url"



# vim: ft=tmux
