# Shell variables
# Generated by 'wal'
wallpaper='/home/th3g3ntl3man/.config/hypr/wallpapers/bg_01.jpg'

# Special
background='#000101'
foreground='#86b7c3'
cursor='#86b7c3'

# Colors
color0='#000101'
color1='#135170'
color2='#205B75'
color3='#19637C'
color4='#145D81'
color5='#1A6B88'
color6='#217A91'
color7='#86b7c3'
color8='#5d8088'
color9='#135170'
color10='#205B75'
color11='#19637C'
color12='#145D81'
color13='#1A6B88'
color14='#217A91'
color15='#86b7c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
