# Shell variables
# Generated by 'wal'
wallpaper='/home/th3g3ntl3man/.config/hypr/wallpapers/bg_08.png'

# Special
background='#000000'
foreground='#f4f4f4'
cursor='#f4f4f4'

# Colors
color0='#000000'
color1='#A6A6A6'
color2='#B9B9B9'
color3='#C7C7C7'
color4='#D7D7D7'
color5='#E9E9E9'
color6='#F3F3F3'
color7='#f4f4f4'
color8='#aaaaaa'
color9='#A6A6A6'
color10='#B9B9B9'
color11='#C7C7C7'
color12='#D7D7D7'
color13='#E9E9E9'
color14='#F3F3F3'
color15='#f4f4f4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
