# Shell variables
# Generated by 'wal'
wallpaper='/home/th3g3ntl3man/.config/hypr/wallpapers/bg_10.png'

# Special
background='#181818'
foreground='#d0cabe'
cursor='#d0cabe'

# Colors
color0='#181818'
color1='#D49721'
color2='#9D8E76'
color3='#447E80'
color4='#AB5F82'
color5='#B26587'
color6='#478688'
color7='#d0cabe'
color8='#918d85'
color9='#D49721'
color10='#9D8E76'
color11='#447E80'
color12='#AB5F82'
color13='#B26587'
color14='#478688'
color15='#d0cabe'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
