[colors.primary]
background = '#111317'
foreground = '#e2e2e8'

[colors.cursor]
text = '#111317'
cursor = '#e2e2e8'

[colors.vi_mode_cursor]
text = '#111317'
cursor = '#a7c8ff'

[colors.search.matches]
foreground = '#424750'
background = '#eeb1fa'

[colors.search.focused_match]
foreground = '#424750'
background = '#a7c8ff'

[colors.footer_bar]
foreground = '#424750'
background = '#e2e2e8'

[colors.hints.start]
foreground = '#424750'
background = '#b8c7e5'

[colors.hints.end]
foreground = '#424750'
background = '#b8c7e5'

[colors.selection]
text = '#c3c6d1'
background = '#424750'


[colors.normal]
black   = '#424750'
red     = '#ffb4ab'
green   = '#a7c8ff'
yellow  = '#b8c7e5'
blue    = '#eeb1fa'
magenta = '#a7c8ff'
cyan    = '#b8c7e5'
white   = '#e2e2e8'


[colors.bright]
black   = '#8d919b'
red     = '#ffb4ab'
green   = '#a7c8ff'
yellow  = '#b8c7e5'
blue    = '#eeb1fa'
magenta = '#a7c8ff'
cyan    = '#b8c7e5'
white   = '#e2e2e8'


[colors.dim]
black   = '#424750'
red     = '#ffb4ab'
green   = '#a7c8ff'
yellow  = '#b8c7e5'
blue    = '#eeb1fa'
magenta = '#a7c8ff'
cyan    = '#b8c7e5'
white   = '#e2e2e8'
