[colors.primary]
background = '#f0f2f7'
foreground = '#4e70c2'

[colors.cursor]
text = '#f0f2f7'
cursor = '#4e70c2'

[colors.vi_mode_cursor]
text = '#f0f2f7'
cursor = '#4e70c2'

[colors.search.matches]
foreground = '#dbdfea'
background = '#4c663b'

[colors.search.focused_match]
foreground = '#dbdfea'
background = '#4e70c2'

[colors.footer_bar]
foreground = '#dbdfea'
background = '#232529'

[colors.hints.start]
foreground = '#dbdfea'
background = '#85539c'

[colors.hints.end]
foreground = '#dbdfea'
background = '#85539c'

[colors.selection]
text = '#4e70c2'
background = '#c8ccd8'


[colors.normal]
black   = '#f0f2f7'
red     = '#e55561'
green   = '#4c663b'
yellow  = '#9e8c6b'
blue    = '#4e70c2'
magenta = '#85539c'
cyan    = '#569b9f'
white   = '#6a708a'


[colors.bright]
black   = '#939ab7'
red     = '#d26e7a'
green   = '#5e7250'
yellow  = '#9e8c6b'
blue    = '#5e7bba'
magenta = '#85539c'
cyan    = '#569b9f'
white   = '#6a708a'


[colors.dim]
black   = '#f0f2f7'
red     = '#e55561'
green   = '#4c663b'
yellow  = '#9e8c6b'
blue    = '#4e70c2'
magenta = '#85539c'
cyan    = '#569b9f'
white   = '#6a708a'
