#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$HOME/.config/rofi/askpass.rasi"

# Rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -normal-window \
     -theme ${RASI}
