#!/usr/bin/env bash

sudo apt install -y libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386

sudo apt install -y qemu-kvm-x86 libvirt-daemon-system libvirt-clients bridge-utils cpu-checker

echo "Android Studio dependencies installed "

exit 0

#vim ft: sh
