#!/usr/bin/env bash
set -eo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Set CPU Mode
##?
##? Usage:
##?   cpumode current|powersave|performance

# usage menu
function show_usage() { #{{{
  echo -e "USAGE:\t$0 powersave|performance|current"
  echo -e "\t\tpowersave\tSet CPU in power-saving mode."
  echo -e "\t\tperformance\tSet CPU in performance mode."
  echo -e "\t\tcurrent\t\tShow the current CPU mode."
  echo -e "\t\thelp\t\tShow this menu."
  exit 1
} #}}}

# our error exit function
function ee() { #{{{
  echo "$1"
  exit 1
} #}}}

# get cpu mode
function getcpumode() { #{{{
  cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
} #}}}

# set cpu mode
function setcpumode() { #{{{
  [ "$1" != 'powersave' -a "$1" != 'performance' -a "$1" != 'schedutil' ] && ee 'Invalid given value..'
  [ $(getcpumode) == "$1" ] && ee "It's already in '$1' mode"
  echo "$1" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
} #}}}

function setpowerprofile() {
  # if powerprofiulesctl exists run powerprofiulesctl set "$1"
  if command -v powerprofilesctl &>/dev/null; then
    sudo powerprofilesctl set "$1"
  else
    ee "powerprofilesctl not found"
  fi
}

function getpowerprofile() {
  if command -v powerprofilesctl &>/dev/null; then
    powerprofilesctl get
  else
    ee "powerprofilesctl not found"
  fi
}

# get & set actions
case "$1" in #{{{
performance)
  setcpumode performance
  setpowerprofile performance
  exit 0
  ;;
schedutil)
  setcpumode schedutil
  setpowerprofile balanced
  exit 0
  ;;
powersave)
  setcpumode powersave
  setpowerprofile power-saver
  exit 0
  ;;
current | get)
  getcpumode
  getpowerprofile
  exit 0
  ;;
help) show_usage ;;
*) ee "Try: $0 help" ;;
esac #}}}

schedutil
