import = [
  "~/.config/alacritty/colors.toml",
  "~/.config/alacritty/fonts.toml",
]


[window]
decorations = "full"
dynamic_title = true
opacity = 0.85
startup_mode = "Maximized"
padding.x = 10
padding.y = 10

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

# start zsh then attach to a consistent tmux session that lives beyond quitting the app
[shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux new-session -A -s main-alacritty"]

[selection]
save_to_clipboard = true
