import = [
  "/home/jvegaf/.config/alacritty/colors.toml",
  "/home/jvegaf/.config/alacritty/fonts.toml",
]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.85
startup_mode = "Maximized"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 12
y = 12

[shell]
program = "/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]
