
[terminal.shell]
program = "/bin/zsh"
args = ["--login", "-c", "tmux new-session -A -s main-alacritty"]

[window]
decorations = "full"
dynamic_title = true
opacity = 0.85
startup_mode = "Maximized"
padding.x = 10
padding.y = 10

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"


[selection]
save_to_clipboard = true

[env]
# TERM = "tmux-256color"
# TERM = "alacritty"
WINIT_X11_SCALE_FACTOR= '1.0'

[general]
import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

# [terminal]
