[font]
size = 12

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

# [font.bold]
# family = "DejaVuSansM Nerd Font"
# style = "Bold"

# [font.bold_italic]
# family = "DejaVuSansM Nerd Font"
# style = "Bold Italic"

# [font.italic]
# family = "DejaVuSansM Nerd Font"
# style = "Italic"



# family = "JetBrainsMono NF"


# [font.bold]
# family = "Hack Nerd Font "
# style = "Bold"
#
# [font.italic]
# family = "Hack Nerd Font "
# style = "Italic"
#
# [font.normal]
# family = "Hack Nerd Font "
# style = "Regular"
#
# [font.bold_italic]
# family = "Hack Nerd Font "
# style = "Italic"
