[font]
size = 10

[font.normal]
family = "ComicCodeLigatures NF"
style = "Regular"

[font.bold]
family = "ComicCodeligatures NF"
style = "Bold"

[font.bold_italic]
family = "ComicCodeLigatures NF"
style = "Bold Italic"

[font.italic]
family = "ComicCodeLigatures NF"
style = "Italic"


# family = "ComicCodeLigatures NF"


# [font.bold]
# family = "Hack Nerd Font "
# style = "Bold"
#
# [font.italic]
# family = "Hack Nerd Font "
# style = "Italic"
#
# [font.normal]
# family = "Hack Nerd Font "
# style = "Regular"
#
# [font.bold_italic]
# family = "Hack Nerd Font "
# style = "Italic"
