## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: "JetBrainsMono NF"
    style: Regular

  # Bold font face
  bold:
    family: "JetBrainsMono NF"
    style: Bold

  # Italic font face
  italic:
    family: "JetBrainsMono NF"
    style: Italic

  # Bold italic font face
  bold_italic:
    family: "JetBrainsMono NF"
    style: Bold Italic

  # Point size
  size: 10

  # Offset
  #offset:
  #  x: 0
  #  y: 0

  # Glyph offset
  #glyph_offset:
  #  x: 0
  #  y: 0
