export DOTFILES_PATH="/home/th3g3ntl3man/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export DOTLY_THEME="codely"
export ZIM_HOME="$DOTFILES_PATH/shell/zsh/.zim"
export WEB_BROWSER="firefox"
export FILE_BROWSER="thunar"
export EDITOR="nvim"
export VISUAL="nvim"
